try{stManager.done('lang100_0.js');}catch(e){}
audio_do_you_want_flash='Желаете ли итти на страницу установки проигрывателя?';
audio_you_need_flash='Ежели Вы желаете слушать композицiи, Вамъ необходимо установить Flash-граммофонъ.';
box_cancel='Отм&#1123;на';
box_close='Затворить';
box_no='Н&#1123;тъ';
box_save='Запомнить';
box_send='Отослать';
box_yes='Да';
captcha_cancel='Отм&#1123;на';
captcha_enter_code='Извольте ввести кодъ съ фотокарточки:';
captcha_send='Отправить';
functions_sure_delete='В&#1123;рно ли, что желаете уничтожить сію запись?';
global_add='Добавить';
global_back='Назадъ';
global_Complain_video='Писать кляузу';
global_cancel='Отм&#1123;на';
global_changes_saved='Изм&#1123;ненія сохранены';
global_charged_zone_title='Предупрежденіе';
global_close='Затворить';
global_continue='Продолжить';
global_delete='Устранить';
global_done='Сд&#1123;лалъ';
global_dont_delete='Не удалять';
global_edit='Изм&#1123;нить';
global_error='Конфузъ';
global_error_occured='Произошелъ конфузъ';
global_media_selector_more='Еще';
global_min='Сложить';
global_money_amount_rub=['','%s рубль','%s рубля','%s рублей'];
global_money_amount_rub_from=['','%s рубль','%s рубля','%s рублей'];
global_money_amount_votes_text=['','голосъ','голоса','голосовъ'];
global_month_label='М&#1123;сяцъ:';
global_num_date_year_time=['','{num_day}.{month}.{short_year} {num_hour}:{minute}','вчера, {num_hour}:{minute}','сегодня, {num_hour}:{minute}','завтра, {num_hour}:{minute}'];
global_n_votes=['','%s ц&#1123;лковый','%s ц&#1123;лковыхъ','%s ц&#1123;лковыхъ'];
global_online=['','Тутъ','Тутъ'];
global_online_sm=['','тутъ','тутъ'];
global_privacy_except='кром&#1123;:';
global_rating_box_header='Престижъ';
global_save='Запомнить';
global_search_not_found='По запросу {search} ничего не найдено.';
global_to_top='Наверхъ';
global_try_to_activate='Утомились, вводимши коды? Не сочтите за трудъ пройти безплатную<br>{link}валидацію черезъ мобильный телефонъ »{/link}';
global_unknown_error='Конфузъ неизв&#1123;стнаго свойства';
global_vkontakte='Въ Контакт&#1123;';
global_warning='Предупрежденіe';
global_write_msg='Отправить письмо';
global_X_people=['','%s персона','%s персоны','%s персонъ'];
global_year_label='Годъ:';
guest_password='Пароль';
Higher_education='Высшее образованiе';
head_fr_online_tip='Доступные нын&#1123; знакомцы';
head_search_results='Вотъ что отыскалось';
Interests='Интересы:';
im_already_shown='Телеграфная служба уже открыта въ Вашемъ обозр&#1123;вател&#1123;, извольте итти въ соотв&#1123;тствующее окно.';
im_already_shown_title='Телеграфъ';
its_spam='Сiе спамъ';
its_spam_sm='Сiе спамъ';
leftAd_Details='Подробн&#1123;е';
leftAd_details='подробн&#1123;е';
leftAd_reminder='Напоминанiе';
left_delete_unpaid_gifts_text='Вы уверены, что хотите удалить все неоплаченные подарки?';
Military_place='Полкъ:';
Month1='Январь';
Month10='Октябрь';
Month10_of='Октября';
Month11='Ноябрь';
Month11_of='Ноября';
Month12='Декабрь';
Month12_of='Декабря';
Month1_of='Января';
Month2='Февраль';
Month2_of='Февраля';
Month3='Мартъ';
Month3_of='Марта';
Month4='Апр&#1123;ль';
Month4_of='Апр&#1123;ля';
Month5='Май';
Month5_of='Мая';
Month6='Iюнь';
Month6_of='Iюня';
Month7='Iюль';
Month7_of='Iюля';
Month8='Августъ';
Month8_of='Августа';
Month9='Сентябрь';
Month9_of='Сентября';
month10sm_of='окт.';
month10_of='октября';
month11sm_of='ноя.';
month11_of='ноября';
month12sm_of='дек.';
month12_of='декабря';
month1sm_of='янв.';
month1_of='января';
month2sm_of='фев.';
month2_of='февраля';
month3sm_of='мар.';
month3_of='марта';
month4sm_of='апр.';
month4_of='апр&#1123;ля';
month5sm_of='мая';
month5_of='мая';
month6sm_of='iюн.';
month6_of='iюня';
month7sm_of='iюл.';
month7_of='iюля';
month8sm_of='авг.';
month8_of='августа';
month9sm_of='сен.';
month9_of='сентября';
pagination_allpages='Вс&#1123;';
privacy_custom_title='Настройки конфиденціальности';
privacy_N_friends_more=['','и ещё %s знакомецъ','и ещё %s знакомца','и ещё %s знакомцевъ'];
privacy_options_advanced_settings='Вс&#1123;мъ, кром&#1123;...';
privacy_options_advanced_settings_dat='вс&#1123;мъ, кром&#1123;...';
privacy_options_all_users='Всякому желающему';
privacy_options_all_users_dat='всякому желающему';
privacy_options_friends_and_friends_dat='знакомцамъ и ихъ знакомцамъ';
privacy_options_friends_only='Однимъ знакомцамъ';
privacy_options_friends_only_dat='однимъ знакомцамъ';
privacy_options_nobody='Никому';
privacy_options_only_me='Мн&#1123; одному';
privacy_options_only_me_dat='мн&#1123; одному';
privacy_options_some_friends='Инымъ знакомцамъ';
privacy_options_some_friends_dat='инымъ знакомцамъ';
privacy_options_some_friend_lists='Инымъ кругамъ знакомцевъ';
privacy_options_some_friend_lists_dat='инымъ кругамъ знакомцевъ';
privacy_save='Запомнить';
Religion='Міровоззр&#1123;нiе';
Remove_from_friends='Порвать знакомство';
rate_you_have_N_unused=['','Въ Вашей казн&#1123; <b>%s</b> ц&#1123;лковый.','Въ Вашей казн&#1123; <b>%s</b> ц&#1123;лковыхъ.','Въ Вашей казн&#1123; <b>%s</b> ц&#1123;лковыхъ.'];
Save='Запомнить';
Secondary_education='Среднее образованiе';
Sex='Полъ:';
Sex_fm='Женскiй';
Sex_m='Мужескiй';
search_by_app='по аппликацiямъ';
search_by_audio='по композицiямъ';
search_by_event='по собранiямъ';
search_by_goods='по товарамъ';
search_by_group='по обществамъ';
search_by_note='по запискамъ';
search_by_person='по персонамъ';
search_by_question='по вопросамъ';
search_by_status='по кондиціямъ';
search_by_topic='по темамъ';
search_by_video='по фильмамъ';
select_chair_select='Укажите названіе';
select_city_not_found='Городъ не найденъ';
select_city_not_selected='- Не выбранъ -';
select_city_select='Укажите названіе';
select_class_not_selected='- Не выбранъ -';
select_country_full_list=' - В&#1123;сь списокъ - ';
select_country_not_found='Держава не найдена';
select_country_select='Укажите государство';
select_district_not_selected='- Не выбранъ -';
select_edustatus_not_selected='- Не выбранъ -';
select_fac_not_selected='- Не выбранъ -';
select_house_not_found='Домъ не найденъ';
select_house_not_selected='- Не выбранъ -';
select_house_select='Укажите нумеръ';
select_place_not_found='Названіе не найдено';
select_place_not_selected='- Не выбрано -';
select_place_select='Укажите названіе';
select_school_not_selected='- Не выбрана -';
select_school_select='Укажите названіе';
select_station_not_selected='- Не выбрана -';
select_street_not_selected='- Не выбрана -';
select_street_select='Укажите названіе';
select_uni_not_selected='- Не выбранъ -';
select_uni_select='Укажите названіе';
sex_fm='женскій';
sex_m='мужескiй';
share_go='Перейти';
Today='Сего дня';
Town='Городъ:';
text_exceeds_symbol_limit=['','Вы изволили превысить допустимый объемъ на %s знакъ.','Вы изволили превысить допустимый объемъ на %s знака.','Вы изволили превысить допустимый объемъ на %s знаковъ.'];
text_N_symbols_remain=['','Остался %s знакъ.','Остались %s знака.','Осталось %s знаковъ.'];
today='сегодня';
Updates='Обновленія';
updates='обновленія';
videofile_num=['','фильма','фильмы','фильмъ'];
votes_flex=['','ц&#1123;лковый','ц&#1123;лковыхъ','ц&#1123;лковыхъ'];
Work_place='М&#1123;сто службы:';
yesterday='вчера';
box_loading='Загрузка...';
box_restore='Восстановить';
claims_flood_error='Вы уже отправили несколько жалоб. Пожалуйста, повторите попытку спустя некоторое время.';
datepicker_date_format='{day} {month} {year}';
datepicker_month_format='{month} {year}';
global_add_media_more='Другое..';
global_captcha_input_here='Введите код сюда';
global_charged_zone_continue='Продолжить';
global_day_label='День:';
global_lang_box_title='Выбор языка';
global_mobile_need_validation='Для этого действия необходима привязка номера телефона. {link}Привязать номер »{/link}';
global_money_amount_rub_text=['','рубль','рубля','рублей'];
global_not_activated_title='Привязка номера телефона';
global_recommended_exceeded=['','Рекомендуемый объем превышен на %s знак.','Рекомендуемый объем превышен на %s знака.','Рекомендуемый объем превышен на %s знаков.'];
global_recommended_lines=['','Рекомендуемый объем превышен на %s строку.','Рекомендуемый объем превышен на %s строки.','Рекомендуемый объем превышен на %s строк.'];
global_reply_to='ответ {user}';
graph_day_fullmon_year_hour='{day} {dayMonth} {year}, {hour}:00';
graph_day_fullmon_year_hour_min='{day} {dayMonth} {year}, {hour}:{min}';
leftAd_news='Новости';
left_delete_unpaid_gifts_title='Удаление подарков';
privacy_N_friends_some=['','и ещё %s друг','и ещё %s друга','и ещё %s друзей'];
select_chair_not_selected='Не выбрана';
select_city_other_city='Другой';
select_country_not_selected='Не выбрана';
select_eduform_not_selected='Не выбрана';
select_street_not_found='Улица не найдена';
top_search='Искать {query}';
top_search_news='Искать {query} в новостях';
// section = 0; version = 49;

friends_no_user_selected='Въ круг&#1123; н&#1123;тъ покам&#1123;стъ ни единой персоны.';
// section = 2; version = 11;

audio_add_to_audio='Включить въ Мои Композиціи';
audio_add_to_group='Добавить въ Музыкальную гостиную Общества';
audio_album_no_recs='Въ папк&#1123; сей покам&#1123;стъ н&#1123;тъ композицiй.';
audio_change_album_name='Изм&#1123;нить названiе';
audio_claim_delete='устранить композицiю';
audio_claim_objection='заполнивъ спецiальную форму';
audio_claim_warning='Композицiя {audio} была изъята изъ публичнаго доступа въ связи съ кляузой правообладателя.';
audio_claim_warning_objection='Композицiя {audio} была изъята изъ публичнаго доступа въ связи съ кляузой правообладателя.<br><br>Вы вольны подать возраженiе, {objection_link}, или {delete_link}.';
audio_claim_warning_text='Композицiя {audio} была изъята изъ публичнаго доступа въ связи съ кляузой правообладателя.<br><br>Вы вольны {delete_link}.';
audio_claim_warning_title='Спорная композицiя';
audio_common_list='общій списокъ';
audio_crap_warning='Грамзапись {audio} была изъята изъ публичнаго доступа въ связи съ разлагающимъ д&#1123;йствіемъ оной композиціи.';
audio_crap_warning_text='Грамзапись {audio} была изъята изъ публичнаго доступа въ связи съ ея непотребнымъ исполненіемъ.<br><br>Вы вольны {delete_link}.';
audio_crap_warning_title='Спорная композицiя';
audio_current_playing_from='Нынче играетъ— {playlist}';
audio_delete='снять';
audio_delete_album='Устранить папку';
audio_delete_album_are_you_sure='В&#1123;рно ли, что Вы желаете устранить папку сiю?';
audio_delete_album_button='Устранить';
audio_delete_album_title='Устраненiе папки';
audio_delete_all_title='Удаленіе композицій';
audio_edit_additionally='Записать текстъ';
audio_edit_album='Изм&#1123;нить папку';
audio_edit_album_title='Изм&#1123;ненiе папки';
audio_edit_cancel='Отм&#1123;на';
audio_edit_deleting='Устраненiе композицiи';
audio_edit_deleting_error='При попытк&#1123; удаленія композицiи изъ репертуара вышелъ конфузъ:';
audio_edit_dont_show_search='Не афишировать въ поиск&#1123;';
audio_edit_edit='Запомнить';
audio_edit_editing='Св&#1123;д&#1123;нiя о композицiи';
audio_edit_name='Названiе:';
audio_edit_no='Н&#1123;тъ';
audio_edit_noname='Безъимянная';
audio_edit_singer='Исполнитель:';
audio_edit_sure_delete='В&#1123;рно ли, что желаете удалить композицiю сiю изъ репертуара?';
audio_edit_text='Текстъ п&#1123;сни:';
audio_edit_unknown='Нев&#1123;домый исполнитель';
audio_edit_yes='Да';
audio_enter_album_name='Извольте ввести названiе';
audio_error_loading='При разм&#1123;щеніи композиціи произошелъ конфузъ. Благоволите обновить страницу.';
audio_export_tip='Включить патефонъ въ салон&#1123;';
audio_friends_feed='Обновления знакомцевъ';
audio_global_search_found=['','Въ поиск&#1123; найдена %s композиція','Въ поиск&#1123; найдено %s композиціи','Въ поиск&#1123; найдено %s композицій'];
audio_group_no_recs='Въ гостиной общества не играютъ покам&#1123;стъ музыки.';
audio_header='Музыкальная гостиная';
audio_loading_error='Произошелъ конфузъ, кодъ: {code}';
audio_lyrics_not_found='Слова песни не найдены';
audio_need_flash_title='Надобенъ Flash-граммофонъ';
audio_new_album_title='Новая папка';
audio_not_found='Композиція не найдена';
audio_no_audios_found='По запросу {query} не найдено ни единой композиціи';
audio_no_rec_load_msg='Здесь Вы можете хранить Ваши музыкальныя композиціи.<br>Для того, чтобы разм&#1123;стить Вашу первую композицію, {link}нажмите зд&#1123;сь{/link}.';
audio_no_your_recs='У Васъ еще н&#1123;тъ композицій';
audio_only_foreign_music='только заграничныя';
audio_popular_audios='Популярныя композицiи';
audio_recommended_audios='Рекомендуемыя композиціи';
audio_repeat_tooltip='Повторять сію композицію';
audio_search_enter_audio_name='Извольте указать названiе или же исполнителя';
audio_search_not_found='Похожихъ на {search} композицiй не изв&#1123;стно.';
audio_search_results='Вотъ что отыскалось';
audio_show_more_audios='Показать больше композицій';
audio_show_recommendations='Узр&#1123;ть подобныя';
audio_shuffle='Перем&#1123;шать';
audio_success_msg_multiple='Вс&#1123; композиціи усп&#1123;шно разм&#1123;щены.';
audio_title_search='Поискъ композицій по запросу {q}';
audio_uploading_over='Разм&#1123;щеніе завершено';
audio_upl_not_enabled_ingroup='Въ семъ обществ&#1123; н&#1123;тъ Музыкальной гостиной, поэтому загрузка композицій невозможна.';
audio_user_no_recs='Въ гостиной персоны сей не изволятъ покам&#1123;стъ играть музыки.';
// section = 3; version = 15;

apps_addapp='Приспособить аппликацiю';
apps_addedtogroup='Аппликацiя добавлена къ клубу.';
apps_app_settings='Настройки аппликацiи';
apps_balance_minus_X_done=['','Вы опустошили казну аппликацiи на <b>%s</b> ц&#1123;лковый.','Вы опустошили казну аппликацiи на <b>%s</b> ц&#1123;лковыхъ.','Вы опустошили казну аппликацiи на <b>%s</b> ц&#1123;лковыхъ.'];
apps_balance_plus_X_done=['','Вы пополнили казну аппликацiи на <b>%s</b> ц&#1123;лковый.','Вы пополнили казну аппликацiи на <b>%s</b> ц&#1123;лковыхъ.','Вы пополнили казну аппликацiи на <b>%s</b> ц&#1123;лковыхъ.'];
apps_cancel='Отм&#1123;на';
apps_change_settings='Изм&#1123;нить';
apps_delete_admin_title='Удаленіе администратора';
apps_done='Ну вотъ&#33;';
apps_dont_show='Больше не показывать';
apps_edit='изм&#1123;нить';
apps_editapp='Изм&#1123;нить';
apps_global_search_found=['','Въ поиск&#1123; найдена %s аппликацiя','Въ поиск&#1123; найдено %s аппликацiи','Въ поиск&#1123; найдено %s аппликацiй'];
apps_last_notifications='Последнiя ув&#1123;домленiя';
apps_merchant_payment_title='Оплата покупки';
apps_my_apps='Мои аппликацiи';
apps_need_X_votes=['','Аппликацiя требуетъ <b>%s</b> ц&#1123;лковый.','Аппликацiя требуетъ <b>%s</b> ц&#1123;лковыхъ.','Аппликацiя требуетъ <b>%s</b> ц&#1123;лковыхъ.'];
apps_noappsingroup2='Обществомъ не приспособлено ни единой аппликаціи.';
apps_no_apps_found='По запросу {query} не найдено ни одного приложения.';
apps_no_notifications='Нетъ опов&#1123;щеній';
apps_of_group='Аппликацiи общества';
apps_remove='Устранить';
apps_search_in_apps='Поискъ по аппликацiям';
apps_show_more_apps='Узр&#1123;ть бол&#1123; аппликацiй';
apps_X_apps_found=['','Им&#1123;ется %s аппликацiя','Им&#1123;ются %s аппликацiи','Им&#1123;ется %s аппликацiй'];
apps_youaddednoapps='Вы не соблаговолили приспособить ни единой аппликацiи.';
app_comments_hidecomms='Сокрыть зам&#1123;чанiя';
app_comments_showcomms='Показать зам&#1123;чанiя';
apps_you_have_no_notifies='У Вас нет ни одного оповещения';
// section = 4; version = 2;

video_add_to_public='Вернуть въ циркуляцiю';
video_comment_placeholder='Высказать зам&#1123;чаніе...';
video_delete_from_public='Изъять изъ циркуляцiи';
video_delete_tag='Снять отм&#1123;тку';
video_flash_needed='Для показа фильмъ необходимъ нов&#1123;йший {flash_player}.';
// section = 5; version = 31;

notes_cancel='Отм&#1123;на';
notes_done='Готово';
notes_livejournal_delete='Удалить сію запись изъ <b>LiveJournal</b>.';
// section = 7; version = 1;

blank_note_not_found='Записка не найдена';
// section = 10; version = 1;

events_fri='Пт';
events_goto_search='Перейти къ поиску';
events_mon='Пн';
events_sat='Сб';
events_sun='Вс';
events_thu='Чт';
events_tue='Вт';
events_wed='Ср';
events_ajax_inv_declined_spam='Приглашение отклонено и помечено как спам.';
// section = 13; version = 1;

fave_return_to_fave='назадъ къ Бумажнику';
// section = 14; version = 4;

gifts_cansend_X_gifts=['','Вы вольны отослать не бол&#1123;е <b>%s</b> презента.','Вы вольны отослать не бол&#1123;е <b>%s</b> презентовъ.','Вы вольны отослать не бол&#1123;е <b>%s</b> презентовъ.'];
gifts_confirm_N_Votes=['','<b>%s</b> ц&#1123;лковый','<b>%s</b> ц&#1123;лковыхъ','<b>%s</b> ц&#1123;лковыхъ'];
gifts_confirm_send_to_N_friends=['','Презентъ будетъ отосланъ %s знакомцу ({votes}). Желаете продолжать?','Презентъ будетъ отосланъ %s знакомцамъ ({votes}). Желаете продолжать?','Презентъ будетъ отосланъ %s знакомцамъ ({votes}). Желаете продолжать?'];
gifts_free_send_left=['','Вы изволили выбрать безплатный презентъ и вольны отослать его <b>%s знакомцу</b>.','Вы изволили выбрать безплатный презентъ и вольны отослать  его <b>%s знакомцамъ</b>.','Вы выбрали  выбрать безплатный презентъ и вольны отослать его <b>%s знакомцамъ</b>.'];
gifts_rate_increase='Буде Вы пошлете сей презентъ, престижъ получателя возрастетъ на <b>{gifts_count}</b>.';
gifts_X_gifts=['','<b>%s</b> презентъ','<b>%s</b> презента','<b>%s</b> презентовъ'];
gifts_X_votes=['','%s ц&#1123;лковый','%s ц&#1123;лковыхъ','%s ц&#1123;лковыхъ'];
// section = 15; version = 6;

groups_admins='Правленіе';
groups_admins_of_group='Правленіе Общества';
groups_appl_rejected='Въ прошенiи отказано.';
groups_assign='Назначить';
groups_assigned='Персона сiя возвышена въ правленiе общества.';
groups_assigning_manager='Назначенiе правленiя';
groups_cancel='Отм&#1123;на';
groups_cancel2='Отм&#1123;нить';
groups_create_enter='Извольте указать названiе общества';
groups_create_new='Устроенiе новаго общества';
groups_delete_manager='Разжалованiе члена правленiя';
groups_deleting_link='Удаленіе отсылу';
groups_edit='Изм&#1123;нить';
groups_editing_link='Изм&#1123;ненiе отсыла';
groups_enter_name='Извольте указать названiе:';
groups_enter_post='Укажите чинъ:';
groups_group_admin='Членъ президиума';
groups_group_create_button='Устроить общество';
groups_inv_cancelled='Приглашенiе отозвано.';
groups_limit_message='Къ сожал&#1123;нію, Вы не можете быть подписаны бол&#1123;е, ч&#1123;мъ на 5000 обществъ или представительствъ одновременно.';
groups_limit_title='Достигнутъ пред&#1123;лъ';
groups_no='Н&#1123;тъ';
groups_officers='Правленiе';
groups_officers_of_group='Руководители Общества';
groups_partic_accepted='Персона сiя прошла инициацiю.';
groups_partic_deleted='Персона сiя изгнана изъ общества.';
groups_reject_invint='Отвергнуть приглашенiе';
groups_sure_delete_link='В&#1123;рно ли, что желаете Вы порвать отношенiя съ симъ обществомъ?';
groups_sure_delete_manager='В&#1123;рно ли, что желаете Вы разжаловать персону сiю, лишивъ всякихъ привилегiй?';
groups_to_all_posts='ко вс&#1123;мъ зам&#1123;ткамъ';
groups_unbanned='Персона сiя отпущена на волю';
groups_yes='Да';
// section = 17; version = 14;

help_ccform_legal_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccform_legal_need_inform='Вы должны выразить своё согласие на обработку Администрацией Сайта Ваших персональных данных, указанных в заявлении, а также на то, что сведения, указанные в заявлении (включая персональные данные) и само заявление будут направлены Администрацией Сайта лицу, указанному Вами в качестве пользователя, разместившего спорный контент, а также могут быть направлены лицу, оспаривающему заявление.';
help_ccform_legal_need_is_owner='Вы должны подтвердить, что являетесь уполномоченным представителем правообладателя указанного спорного контента.';
help_ccform_legal_need_perjury='Вы должны подтвердить, что осознаете юридические последствия, которые может повлечь ложное обвинение в нарушении авторских прав.';
help_ccform_legal_need_unauthorized='Вы должны подтвердить, что спорный контент используется без согласия правообладателя.';
help_ccform_natural_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccform_natural_need_inform='Вы должны выразить своё согласие на обработку Администрацией Сайта Ваших персональных данных, указанных в заявлении, а также на то, что сведения, указанные в заявлении (включая персональные данные) и само заявление будут направлены Администрацией Сайта лицу, указанному Вами в качестве пользователя, разместившего спорный контент, а также могут быть направлены лицу, оспаривающему заявление.';
help_ccform_natural_need_owner='Вы должны подтвердить, что являетесь правообладателем указанного спорного контента.';
help_ccform_natural_need_perjury='Вы должны подтвердить, что осознаете юридические последствия, которые может повлечь ложное обвинение в нарушении авторских прав.';
help_ccform_natural_need_unauthorized='Вы должны подтвердить, что спорный контент используется без Вашего разрешения.';
help_ccform_need_rules='Вы должны согласиться с условиями правил рассмотрения заявлений, связанных с размещением контента на сайте ВКонтакте.';
help_ccobjection_need_email='Вы должны выразить согласие с тем, что указанный Вами адрес электронной почты может использоваться Администрацией Сайта для дальнейших коммуникаций по заявлению.';
help_ccobjection_need_inform='Вы должны выразить своё согласие с тем, что указанные выше данные о Вас и Ваше возражение будут направлены правообладателю.';
help_ccobjection_need_rules='Вы должны согласиться с условиями правил рассмотрения заявлений, связанных с размещением контента на сайте ВКонтакте.';
// section = 18; version = 1;

login_wrong_email_pwd='Вы изволили ввести нев&#1123;рный логинъ либо пароль.';
login_enter='Войти';
// section = 21; version = 1;

mail_added_link='Отсылъ';
mail_cancel='Отм&#1123;на';
mail_close='Затворить';
mail_delete='Сжечь';
mail_deleteall1='Сжечь вс&#1123; письма';
mail_delete_all_spam='Сжечь вс&#1123; сообщенія, содержащія спамъ?';
mail_error='Конфузъ';
mail_marked_as_spam='Письмо сочтено спамомъ и уничтожено незамедлительно.';
// section = 22; version = 31;

payments_amount_votes=['','ц&#1123;лковый','ц&#1123;лковыхъ','ц&#1123;лковыхъ'];
payments_cancel='Отм&#1123;на';
payments_card_verified_msg='Вы подтвердили, что являетесь влад&#1123;льцемъ карты.';
payments_error='Конфузъ';
payments_fee_full='Комиссія {amount} р. ({percent}%)';
payments_msg_deleted='Сообщеніе удалено.';
payments_N_tries_left_msg=['','У Васъ осталась одна попытка.','У Васъ осталось %s попытки.','У Васъ осталось %s попытокъ.'];
payments_really_start_over_msg='Вы д&#1123;йствительно хотите начать процедуру заново?';
payments_really_use_other_msg='Вы д&#1123;йствительно хотите использовать другую карту для проведенія платежей?';
payments_thanks_for_comm='Спасибо за Вашъ отзывъ.';
payments_verify_start_over_header='Вы ув&#1123;рены?';
payments_verify_sum_currency='Валюта авторизаціонной транзакціи:';
payments_verify_sum_dialog='Введите сумму авторизаціонной транзакціи:';
payments_verify_sum_howto_dialog='Сумму авторизаціонной транзакціи Вы можете узнать:<br><ul class="listing"><li><span> обратившись въ службу кліентской поддержки банка по телефону, указанному на обратной сторон&#1123; Вашей карты. Сообщите оператору, что Вы только что произвели оплату въ интернетъ-магазин&#1123;, и, для подтвержденія права на использованіе карты, Вамъ необходима информація о сумм&#1123; транзакціи. Васъ попросятъ идентифицировать себя, посл&#1123; чего предоставятъ информацію.</span></li><li><span> черезъ систему удаленнаго банковскаго обслуживанія интернетъ-банкъ/банкъ-кліентъ - въ случа&#1123; предоставленія данной услуги банкомъ-эмитентомъ;</span></li><li><span> cъ помощью услуги S.M.S.-информированія - въ случа&#1123; предоставленія данной услуги банкомъ-эмитентомъ.</span></li></ul>';
payments_verify_sum_howto_header='Какъ узнать сумму авторизаціонной транзакціи';
payments_wait_verifying_msg='Пожалуйста, подождите. Пров&#1123;рка можетъ занять 5-10 минутъ.';
payments_wrong_sum_msg='Сумма авторизаціонной транзакціи введена нев&#1123;рно, попробуйте снова.';
payments_your_comm='Вашъ отзывъ';
payment_no_more_tries_msg='Сумма авторизаціонной транзакціи введена нев&#1123;рно. Вы исчерпали количество попытокъ для этой авторизаціонной транзакціи. Вамъ необходимо запустить процессъ подтвержденія заново, нажавъ кнопку &quot;Авторизовать карту&quot;.';
payments_amount_rubles=['','рубль','рубля','рублей'];
payments_close='Закрыть';
payments_fee_votes=['','Сумма: %s рубль','Сумма: %s рубля','Сумма: %s рублей'];
payments_min_amount_limit_rubles='Минимальная сумма: %s рублей';
payments_payment_system_submit='Оплатить';
payments_please_enter_money='Пожалуйста, введите сумму платежа.';
payments_send='Отправить';
payments_verify_sum_header='Введите сумму';
// section = 28; version = 3;

photos_cancel='Отм&#1123;на';
photos_viewer_exit='Выйти изъ режима просмотра';
photo_comment_marked_as_spam='Вы изволили счесть зам&#1123;чанiе спамнымъ.';
photo_dont_close='Не извольте закрывать окно сiе, пока фотокарточки не будутъ добавлены.';
photo_rotating='Поворачиваемъ';
photo_uploading_photo='Фотокарточки добавляются';
photos_done='Готово';
photos_stop_uploading='Прервать загрузку';
photos_uploading_warning='Загрузка фотографий ещё продолжается. Вы уверены, что хотите покинуть страницу и прервать загрузку?';
// section = 30; version = 4;

ads_image_too_small='Вы пытаетесь разм&#1123;стить слишкомъ маленькую фотокарточку.<br>Благоволите выбрать фотокарточку большаго разм&#1123;ра и повторите попытку.';
profile_enter_post='Высказать зам&#1123;чаніе..';
profile_mention_not_found='Персона не обнаружена';
profile_mention_start_typing='Начните писать имя знакомца или названie общества';
profile_oph_crop_desc='Извольте выд&#1123;лить квадратную область для маленькихъ фотокарточекъ.<br>Сия минiатюра будетъ использована въ Вашихъ известiяхъ, личной корреспонденцiи и комментарiяхъ.';
profile_custom_snippet_photo_error_size='{sorry}.<br>Фотография должна иметь размер не меньше {width} точек в ширину и  {height} точек в высоту.<br>Кроме того, нельзя использовать фотографии, у которых одна из сторон в несколько раз превышает другую.';
// section = 31; version = 14;

reg_sex_not_set='Не задан';
// section = 35; version = 1;

search_nothing_found='Ничего не найдено';
// section = 36; version = 1;

stats_data_empty='Н&#1123;тъ данныхъ';
stats_error_loading='Ошибка при загрузк&#1123;';
stats_no_data='Отсутствуютъ входныя данные';
stats_day_mon='{day} {month}';
stats_day_month_year='{day} {month} {year}';
stats_good_browser_box_msg='К сожалению, Ваш браузер не поддерживает отображение графиков статистики.<br><br>Чтобы использовать все возможности сайта, Вы можете загрузить и установить один из современных браузеров:';
stats_loading='Загрузка...';
// section = 38; version = 2;

paysupp_error='Конфузъ';
// section = 39; version = 16;

wall_post_not_found='Высказыванiе пропало';
wall_publish_now='Разм&#1123;стить в сей же мигъ';
wall_reply_to_post='Высказать зам&#1123;чаніе..';
wall_reply_to_post_link='Высказать зам&#1123;чаніе';
wall_send='Высказать';
// section = 41; version = 17;

vkontakte_ru='В.К.';
// section = 42; version = 3;

fans_block_fan='Внести въ списокъ отверженныхъ';
fans_no_fans='На сію персону покам&#1123;стъ никто не подписанъ.';
fans_no_idols='Сія персона покам&#1123;стъ не подписана ни на одну страницу.';
fans_show_all_fans='Отразить всехъ почитателей ';
fans_show_all_idols='Отразить вс&#1123; занимательныя страницы ';
// section = 54; version = 5;

abuse_goto_support='Ежели Вы желаете порвать поддельный или же свой старый паспортъ, извольте обратиться <a class="wikiVkLink" href="http://vk.com/support?act=new&amp;from=abuse">къ сов&#1123;тникамъ</a>. ';
// section = 58; version = 1;

offers_reban='Вернуть в список';
offers_unban='Удалить из списка';
// section = 59; version = 1;

mobile_apps_catalog_app_members=['','%s челов&#1123;къ','%s челов&#1123;ка','%s челов&#1123;къ'];
mobile_photos_albums_edit_album_btn='Запомнить';
mobile_photos_edit_save_btn='Запомнить';
mobile_profile_work_label='М&#1123;сто службы:';
mobile_wall_publish_postponed='Разм&#1123;стить в сей же мигъ';
mobile_zphoto_save_btn='Запомнить';
mobile_act_not_activated_header='Привязка номера телефона';
mobile_edit_country_null='Не выбрана';
// section = 61; version = 4;

adslight_age_restriction_none='Не указывать';
// section = 67; version = 1;

print_group_change_address='Вы вольны см&#1123;нить адресъ общества въ {link}настройкахъ{/link}.';
print_group_not_found='Общество не найдено';
print_group_no_address='Общество %s не им&#1123;етъ короткаго адреса. Наклейки можно создать лишь для обществъ, у которыхъ есть короткій адресъ вида <b>vk.com/cafe</b>.';
print_group_placeholder='Извольте ввести названіе общества или адресъ страницы';
print_stickers_example='Прим&#1123;ры наклеекъ';
print_close_text='Ваши наклейки в данный момент создаются. Вы уверены, что хотите закрыть страницу?';
print_close_title='Закрыть страницу';
print_epsp_hint='Векторный формат, предназначенный для печатного оборудования.<br>{tag}В файле добавлены вылеты и кривые, по которым наклейка будет вырезаться{/tag}';
print_eps_hint='Векторный формат изображения';
print_flood_error='Действие выполняется слишком часто, пожалуйста, попробуйте повторить попытку позже.';
print_png_hint='Растровый формат изображения';
print_user_change_address='Вы можете изменить адрес своей страницы в {link}настройках{/link}. ';
print_user_no_address='%s не имеет короткого адреса. Наклейки можно создать только для страниц, у которых есть короткий адрес вида <b>vk.com/cafe</b>.';
// section = 69; version = 3;


var langConfig = {"id":100,"numDel":"<span class=\"num_delim\"> <\/span>","numDelS":" ","numDec":",","prepTags":["{prep_with}","{prep_With}","{prep_about}","{prep_About}","{prep_into}","{prep_Into}"],"prep":[["{prep_with},{prep_With}","С*,З*,Льв*","со,Со"],["{prep_with},{prep_With}","*,Са*,Се*,Сё*,Си*,Со*,Су*,Сэ*,Сы*,Сю*,Ся*,За*,Зе*,Зё*,Зи*,Зо*,Зу*,Зэ*,Зю*,Зя*,Зы*","съ,Съ"],["{prep_about},{prep_About}","А*,О*,У*,И*,Э*","объ,Объ"],["{prep_about},{prep_About}","*","о,О"],["{prep_into},{prep_Into}","В*,Ф*,Льв*","во,Во"],["{prep_into},{prep_Into}","*,Ва*,Ве*,Вё*,Ви*,Во*,Ву*,Вы*,Вэ*,Вю*,Вя*,Фа*,Фе*,Фё*,Фи*,Фо*,Фу*,Фэ*,Фю*,Фя*,Фы*","въ,Въ"]],"parent":0,"timeSys":["24hour"],"yearOffset":0,"flexLast":false,"revOrder":false,"RTL":false,"numRules":{"int":[[100,[11,12,13,14],3],[10,[1],1],[10,[2,3,4],2],["*",0,3]],"float":2},"sexRules":[[1,2],["*",1]],"larr":"&larr;","rarr":"&rarr;"};
var market_currency_count = ['RUB','UAH','KZT','USD','EUR'];

var qArr = [[0, getLang('search_by_person'), '', 'people', 0],
[1, getLang('search_by_group'), '', 'groups', 0x00800000],
[2, getLang('search_by_event'), '', 'events', 0x01000000],
[3, getLang('search_by_audio'), '', 'audio',  0x00000002],
[4, getLang('search_by_video'), '', 'video',  0x00400000],
[5, getLang('search_by_ad'), '', 'ads', 0x00000100],
[6, getLang('search_by_app'), '', 'apps', 0x00000020],
[7, getLang('search_by_question'), '', 'questions', 0x00000040],
[8, getLang('search_by_note'), '', 'notes', 0x02000000],
[9, getLang('search_by_topic'), '', 'topics', 0x00800000],
[11, getLang('search_by_status'), '', 'statuses', 0]];

var year_offset = langConfig.yearOffset;
var larr = langConfig.larr;
var rarr = langConfig.rarr;